name: release

on:
  push:
    tags:
      # alternatively, use '*' here for all tag names
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        # get all history and tags
        fetch-depth: 0
    - name: Get release text
      run: python .github/scripts/create_releases.py ${{ github.ref_name }} > release_body.txt
    - name: Create GitHub release
      uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
      with:
        bodyFile: release_body.txt
